// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lgodqqlfrltynbydemcj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imxnb2RxcWxmcmx0eW5ieWRlbWNqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY5NDgwNjAsImV4cCI6MjA2MjUyNDA2MH0.2UoFxlHDRJFA_YPX_iODV_Y4UY8cf4Mb96_Ud790PEo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);